### ISSUE TITLE
Problema após POST

### ISSUE THREAD

**Issue by jacksonveroneze** [mateuscalza/es7-autocomplete#1]
Elemento do form fica desconfigurado após realizar um post e o form falhar na validação.

```
Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
prepareElements @   index.js:2504
StormBox    @   index.js:2479
applyAutocomplete   @   index.js:1263
(anonymous function)    @   criar:735
```

![captura de tela de 2016-07-19 17-11-15](https://cloud.githubusercontent.com/assets/3782911/16964845/d1bc6062-4dd3-11e6-9c58-c3ff9e95fc6f.png)

**Comment by mateuscalza** [comment]
Corrigido! Versão 1.6.7.
Obrigado pelo feedback.

## 

Revised! Version 1.6.7.
Thanks.

**Comment by jacksonveroneze** [comment]
Problema resolvido, vou fechar a issue.
